.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SCAFWRAP" "1" "December 2015" "" ""
.
.SH "NAME"
\fBscafwrap\fR \- Shell wrapper to transparently invoke OpenMP programs as SCAF clients
.
.SH "SYNOPSIS"
\fBscafwrap\fR [application [application\'s arguments]]
.
.SH "DESCRIPTION"
\fBscafwrap\fR is a wrapper which runs OpenMP programs as SCAF clients without the need for recompilation or modification\. Early versions of SCAF required recompiling the GOMP parallel library with a patch and pointing the system\'s linker to the patched runtime, which proved to be cumbersome\. \fBscafwrap\fR aims to be a more portable alternative\.
.
.SH "ENVIRONMENT"
The underlying SCAF runtime that \fBscafwrap\fR uses is affected by the following environment variables:
.
.TP
\fBSCAF_COMM_RATE_LIMIT\fR
Setting this to a floating point value overrides the rate (frequency) at which the client will attempt to communicate with \fBscafd\fR\. E\.g\., setting \fBSCAF_COMM_RATE_LIMIT=50\fR will ensure that the client won\'t check in faster than 50Hz\. The rate limiting is implemented using the token bucket algorithm\. Note that setting this to a negative value has the effect of disabling the limit\. The default value is 5\.0\.
.
.TP
\fBSCAF_MATH_RATE_LIMIT\fR
Setting this to a floating point value overrides the rate (frequency) at which the client will internally instrument sections and compute efficiency results\. E\.g\., setting \fBSCAF_MATH_RATE_LIMIT=50\fR will ensure that sections aren\'t timed (and their parallel efficiencies computed) faster than 50Hz\. In the event that rate limiting requies skipping some sections, the client is essentially \fIsampling\fR parallel sections at the specified rate in order to compute its efficiency\. The rate limiting is implemented using the token bucket algorithm\. Note that setting this to a negative value has the effect of disabling the limit\. The default value is 32\.0\.
.
.TP
\fBSCAF_DISABLE_EXPERIMENTS\fR
Setting this to a non\-zero integer disables serial experimental entirely\. You probably only want to do this to debug serial experiments themselves\. Performance feedback is unlikely to be useful with experiments disabled\. The default value is 0\.
.
.TP
\fBSCAF_EXPERIMENT_MIN_USECONDS\fR
Serial experiments will run (if safe) for at least the specified number of microseconds, even if the non\-experimental parallel sections are finished and program progress is waiting for the experiment to finish\. A value too large will cause an excess of these waits, while a value too small may result in experiment results which are unreliable\. The default is 100000 useconds\.
.
.TP
\fBSCAF_LAZY_EXPERIMENTS\fR
By default, serial experiments do not run unless there are multiple SCAF clients\. (A single client should probably just run on the entire machine, so performance feedback would not be useful\.) If a second client arrives, then all clients will begin executing experiments\. Setting \fBSCAF_LAZY_EXPERIMENTS=0\fR disables this behavior, and all clients will run serial experiments even if they are alone on the machine\.
.
.TP
\fBSCAF_SECTION_DUMPS\fR
Setting this to a non\-zero integer enables verbose logging of every parallel section to \fB/tmp/scaf\-sectiondump\.${PID}\.csv\fR\. This can be used to examine the timing and nature of parallel sections in your program\. If enabled, \fIall\fR sections will be accounted for in this file regardless of the values of \fBSCAF_COMM_RATE_LIMIT\fR and \fBSCAF_MATH_RATE_LIMIT\fR\. Note that this option may have a significant performance impact\.
.
.TP
\fBSCAF_NOT_MALLEABLE\fR
Setting this to a non\-zero integer notifies the SCAF runtime that the process is known to be NOT malleable\. Although SCAF can generally detect non\-malleable processes dynamically without this hint, sometimes higher performance can be achieved if it is explicitly known to be non\-malleable before execution begins\.
.
.SH "EXAMPLES"
.
.SS "Example 1: Running NAS benchmarks"
.
.nf

$ scafwrap \./cg\.B\.x &
$ scafwrap \./lu\.B\.x &
$ wait
.
.fi
.
.SH "AUTHOR"
Tim Creech \fItcreech@umd\.edu\fR
.
.SH "SEE ALSO"
scafd(1)
